backend:
  name: git-gateway
  branch: main

site_url: https://jovial-custard-0f6a05.netlify.app

media_folder: "images/uploads"     # nơi LƯU ảnh trong repo
public_folder: "/images/uploads"    # đường dẫn công khai để website hiển thị

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "posts"          # <— thư mục chứa các bài viết (markdown)
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Ảnh đại diện", name: "thumbnail", widget: "image", required: false }
      - { label: "Nội dung", name: "body", widget: "markdown" }
