backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày", name: "date", widget: "datetime" }
      - { label: "Ảnh đại diện", name: "thumbnail", widget: "image", required: false }
      - { label: "Nội dung", name: "body", widget: "markdown" }

  - name: "vac"
    label: "VAC – Mô hình sinh thái"
    folder: "vac"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày", name: "date", widget: "datetime" }
      - { label: "Ảnh minh hoạ", name: "cover", widget: "image", required: false }
      - { label: "Tóm tắt ngắn", name: "excerpt", widget: "text", required: false }
      - { label: "Nội dung chi tiết", name: "body", widget: "markdown" }
